# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Iinclude
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lm -lX11
LDDEPS +=
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = bin/debug
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/debug/.build/obj/x64/debug/canim
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -Wl,--whole-archive bin/debug/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/debug/include"
	cp -rf include/raylib "bin/debug/include/"
	cp -f include/canim.h "bin/debug/include/canim.h"
endef

else ifeq ($(config),debug_x86)
TARGETDIR = bin/debug
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/debug/.build/obj/x86/debug/canim
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -g
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -Wl,--whole-archive bin/debug/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/debug/include"
	cp -rf include/raylib "bin/debug/include/"
	cp -f include/canim.h "bin/debug/include/canim.h"
endef

else ifeq ($(config),debug_arm64)
TARGETDIR = bin/debug
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/debug/.build/obj/ARM64/debug/canim
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS) -Wl,--whole-archive bin/debug/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/debug/include"
	cp -rf include/raylib "bin/debug/include/"
	cp -f include/canim.h "bin/debug/include/canim.h"
endef

else ifeq ($(config),sanitize_x64)
TARGETDIR = bin/sanitize
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/sanitize/.build/obj/x64/sanitize/canim
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fsanitize=address -fsanitize=undefined -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fsanitize=address -fsanitize=undefined -g
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -fsanitize=address -fsanitize=undefined -Wl,--whole-archive bin/sanitize/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/sanitize/include"
	cp -rf include/raylib "bin/sanitize/include/"
	cp -f include/canim.h "bin/sanitize/include/canim.h"
endef

else ifeq ($(config),sanitize_x86)
TARGETDIR = bin/sanitize
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/sanitize/.build/obj/x86/sanitize/canim
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -fsanitize=address -fsanitize=undefined -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -fsanitize=address -fsanitize=undefined -g
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -fsanitize=address -fsanitize=undefined -Wl,--whole-archive bin/sanitize/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/sanitize/include"
	cp -rf include/raylib "bin/sanitize/include/"
	cp -f include/canim.h "bin/sanitize/include/canim.h"
endef

else ifeq ($(config),sanitize_arm64)
TARGETDIR = bin/sanitize
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/sanitize/.build/obj/ARM64/sanitize/canim
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -fsanitize=address -fsanitize=undefined -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -fsanitize=address -fsanitize=undefined -g
ALL_LDFLAGS += $(LDFLAGS) -fsanitize=address -fsanitize=undefined -Wl,--whole-archive bin/sanitize/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/sanitize/include"
	cp -rf include/raylib "bin/sanitize/include/"
	cp -f include/canim.h "bin/sanitize/include/canim.h"
endef

else ifeq ($(config),release_x64)
TARGETDIR = bin/release
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/release/.build/obj/x64/release/canim
DEFINES += -DNDEBUG -DALTARR_NO_DIAGNOSTICS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -Wl,--whole-archive bin/release/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/release/include"
	cp -rf include/raylib "bin/release/include/"
	cp -f include/canim.h "bin/release/include/canim.h"
endef

else ifeq ($(config),release_x86)
TARGETDIR = bin/release
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/release/.build/obj/x86/release/canim
DEFINES += -DNDEBUG -DALTARR_NO_DIAGNOSTICS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -s -Wl,--whole-archive bin/release/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/release/include"
	cp -rf include/raylib "bin/release/include/"
	cp -f include/canim.h "bin/release/include/canim.h"
endef

else ifeq ($(config),release_arm64)
TARGETDIR = bin/release
TARGET = $(TARGETDIR)/canim
OBJDIR = bin/release/.build/obj/ARM64/release/canim
DEFINES += -DNDEBUG -DALTARR_NO_DIAGNOSTICS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s -Wl,--whole-archive bin/release/.build/lib/libraylib.a -Wl,--no-whole-archive -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir -p "bin/release/include"
	cp -rf include/raylib "bin/release/include/"
	cp -f include/canim.h "bin/release/include/canim.h"
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/loader.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/render.o
GENERATED += $(OBJDIR)/rl_rendertexture_msaa.o
GENERATED += $(OBJDIR)/timeline.o
OBJECTS += $(OBJDIR)/loader.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/render.o
OBJECTS += $(OBJDIR)/rl_rendertexture_msaa.o
OBJECTS += $(OBJDIR)/timeline.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking canim
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning canim
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/loader.o: src/core/loader.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/render.o: src/core/render.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/timeline.o: src/core/timeline.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rl_rendertexture_msaa.o: src/extra/rl_rendertexture_msaa.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/main.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif